package com.xiaomingming.api.vo;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("fo_forder", "id", FoForder.class);
		arp.addMapping("hi_histroy", "id", HiHistroy.class);
		arp.addMapping("in_interface", "id", InInterface.class);
		arp.addMapping("pa_param", "id", PaParam.class);
		arp.addMapping("pr_project", "id", PrProject.class);
		arp.addMapping("re_response", "id", ReResponse.class);
		arp.addMapping("us_user", "id", UsUser.class);
		arp.addMapping("user_project", "id", UserProject.class);
	}
}

