package com.xiaomingming.api.vo;

import com.xiaomingming.api.vo.base.BaseFoForder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FoForder extends BaseFoForder<FoForder> {
	
}
