package com.xiaomingming.api.vo;

import com.xiaomingming.api.vo.base.BaseHiHistroy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HiHistroy extends BaseHiHistroy<HiHistroy> {
	
}
