package com.xiaomingming.api.vo;

import com.xiaomingming.api.vo.base.BaseInInterface;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InInterface extends BaseInInterface<InInterface> {
	
}
