package com.xiaomingming.api.vo;

import com.xiaomingming.api.vo.base.BasePaParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaParam extends BasePaParam<PaParam> {
	
}
