package com.xiaomingming.api.vo;

import com.xiaomingming.api.vo.base.BasePrProject;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrProject extends BasePrProject<PrProject> {

    public List<FoForder> foders = new ArrayList<FoForder>();
}
