package com.xiaomingming.api.vo;

import com.xiaomingming.api.vo.base.BaseReResponse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReResponse extends BaseReResponse<ReResponse> {
	
}
