package com.xiaomingming.api.vo;

import com.xiaomingming.api.vo.base.BaseUserProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserProject extends BaseUserProject<UserProject> {
	
}
