package com.xiaomingming.api.vo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaParam<M extends BasePaParam<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPaKey(java.lang.String paKey) {
		set("pa_key", paKey);
	}
	
	public java.lang.String getPaKey() {
		return getStr("pa_key");
	}

	public void setPaValue(java.lang.String paValue) {
		set("pa_value", paValue);
	}
	
	public java.lang.String getPaValue() {
		return getStr("pa_value");
	}

	public void setPaExample(java.lang.String paExample) {
		set("pa_example", paExample);
	}
	
	public java.lang.String getPaExample() {
		return getStr("pa_example");
	}

	public void setInId(java.lang.Integer inId) {
		set("in_id", inId);
	}
	
	public java.lang.Integer getInId() {
		return getInt("in_id");
	}

}
