package com.xiaomingming.api.vo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserProject<M extends BaseUserProject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUsId(java.lang.Integer usId) {
		set("us_id", usId);
	}
	
	public java.lang.Integer getUsId() {
		return getInt("us_id");
	}

	public void setPrId(java.lang.Integer prId) {
		set("pr_id", prId);
	}
	
	public java.lang.Integer getPrId() {
		return getInt("pr_id");
	}

}
