package com.xiaomingming.api.vo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsUser<M extends BaseUsUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUsEmail(java.lang.String usEmail) {
		set("us_email", usEmail);
	}
	
	public java.lang.String getUsEmail() {
		return getStr("us_email");
	}

	public void setUsPass(java.lang.String usPass) {
		set("us_pass", usPass);
	}
	
	public java.lang.String getUsPass() {
		return getStr("us_pass");
	}

	public void setUsName(java.lang.String usName) {
		set("us_name", usName);
	}
	
	public java.lang.String getUsName() {
		return getStr("us_name");
	}

	public void setUsIcon(java.lang.String usIcon) {
		set("us_icon", usIcon);
	}
	
	public java.lang.String getUsIcon() {
		return getStr("us_icon");
	}

	public void setUsMobile(java.lang.String usMobile) {
		set("us_mobile", usMobile);
	}
	
	public java.lang.String getUsMobile() {
		return getStr("us_mobile");
	}

	public void setUsOpenid(java.lang.Integer usOpenid) {
		set("us_openid", usOpenid);
	}
	
	public java.lang.Integer getUsOpenid() {
		return getInt("us_openid");
	}

	public void setUsRegestTime(java.lang.Integer usRegestTime) {
		set("us_regest_time", usRegestTime);
	}
	
	public java.lang.Integer getUsRegestTime() {
		return getInt("us_regest_time");
	}

	public void setUsLastTime(java.lang.Integer usLastTime) {
		set("us_last_time", usLastTime);
	}
	
	public java.lang.Integer getUsLastTime() {
		return getInt("us_last_time");
	}

}
