package com.xiaomingming.api.vo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReResponse<M extends BaseReResponse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setReContent(java.lang.String reContent) {
		set("re_content", reContent);
	}
	
	public java.lang.String getReContent() {
		return getStr("re_content");
	}

	public void setReType(java.lang.Integer reType) {
		set("re_type", reType);
	}
	
	public java.lang.Integer getReType() {
		return getInt("re_type");
	}

	public void setInId(java.lang.Integer inId) {
		set("in_id", inId);
	}
	
	public java.lang.Integer getInId() {
		return getInt("in_id");
	}

}
