package com.xiaomingming.api.vo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInInterface<M extends BaseInInterface<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInName(java.lang.String inName) {
		set("in_name", inName);
	}
	
	public java.lang.String getInName() {
		return getStr("in_name");
	}

	public void setInUrl(java.lang.String inUrl) {
		set("in_url", inUrl);
	}
	
	public java.lang.String getInUrl() {
		return getStr("in_url");
	}

	public void setInMethod(java.lang.String inMethod) {
		set("in_method", inMethod);
	}
	
	public java.lang.String getInMethod() {
		return getStr("in_method");
	}

	public void setInDocument(java.lang.String inDocument) {
		set("in_document", inDocument);
	}
	
	public java.lang.String getInDocument() {
		return getStr("in_document");
	}

	public void setInType(java.lang.Integer inType) {
		set("in_type", inType);
	}
	
	public java.lang.Integer getInType() {
		return getInt("in_type");
	}

	public void setFoId(java.lang.Integer foId) {
		set("fo_id", foId);
	}
	
	public java.lang.Integer getFoId() {
		return getInt("fo_id");
	}

	public void setInResponseOk(java.lang.String inResponseOk) {
		set("in_response_ok", inResponseOk);
	}
	
	public java.lang.String getInResponseOk() {
		return getStr("in_response_ok");
	}

	public void setInResponseErr(java.lang.String inResponseErr) {
		set("in_response_err", inResponseErr);
	}
	
	public java.lang.String getInResponseErr() {
		return getStr("in_response_err");
	}

}
