package com.xiaomingming.api.vo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrProject<M extends BasePrProject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPrName(java.lang.String prName) {
		set("pr_name", prName);
	}
	
	public java.lang.String getPrName() {
		return getStr("pr_name");
	}

	public void setPrCreateTime(java.lang.Integer prCreateTime) {
		set("pr_create_time", prCreateTime);
	}
	
	public java.lang.Integer getPrCreateTime() {
		return getInt("pr_create_time");
	}

	public void setPrRootUrl(java.lang.String prRootUrl) {
		set("pr_root_url", prRootUrl);
	}
	
	public java.lang.String getPrRootUrl() {
		return getStr("pr_root_url");
	}

}
